openapi: 3.0.3
info:
  title: Products API
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/products:
    get:
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Product list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: integer }
                        name: { type: string }
                        price: { type: number }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
